<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXlERB0i\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXlERB0i/Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXlERB0i.legacy');

    return;
}

if (!\class_exists(Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXlERB0i\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false);
}

return new \ContainerXlERB0i\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer([
    'container.build_hash' => 'XlERB0i',
    'container.build_id' => '759b3f43',
    'container.build_time' => 1672816414,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXlERB0i');
