<?php

namespace ContainerCaieTnk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_OyBxp7UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.OyBxp7U' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Messenger/Handler/GenerateWeb2PrintPdfHandler.php';

        return $container->privates['.messenger.handler_descriptor.OyBxp7U'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Pimcore\Messenger\Handler\GenerateWeb2PrintPdfHandler(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService())), []);
    }
}
