<?php

namespace Container834codi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GWhRGQHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gWhRGQH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gWhRGQH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'configWriter' => ['privates', 'Pimcore\\Config\\ReportConfigWriter', 'getReportConfigWriterService', true],
        ], [
            'configWriter' => 'Pimcore\\Config\\ReportConfigWriter',
        ]);
    }
}
