<?php

namespace Container1e96TnN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getControllerEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BWKyjX5.Symfony\Component\HttpKernel\Event\ControllerEvent' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Event\ControllerEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.BWKyjX5": it references class "Symfony\\Component\\HttpKernel\\Event\\ControllerEvent" but no such service exists.');
    }
}
