<?php

namespace ContainerIz9Nwpv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MSAu7MbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MSAu7Mb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MSAu7Mb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'provider' => ['services', 'Pimcore\\Controller\\Config\\ControllerDataProvider', 'getControllerDataProviderService', true],
        ], [
            'provider' => 'Pimcore\\Controller\\Config\\ControllerDataProvider',
        ]);
    }
}
