<?php

namespace Container6vBF2Ok;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldDefinitionDocBlockBuilderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\DataObject\ClassBuilder\FieldDefinitionDocBlockBuilderInterface' shared autowired service.
     *
     * @return \Pimcore\DataObject\ClassBuilder\FieldDefinitionDocBlockBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/DataObject/ClassBuilder/FieldDefinitionDocBlockBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/DataObject/ClassBuilder/FieldDefinitionDocBlockBuilder.php';

        return $container->services['Pimcore\\DataObject\\ClassBuilder\\FieldDefinitionDocBlockBuilderInterface'] = new \Pimcore\DataObject\ClassBuilder\FieldDefinitionDocBlockBuilder();
    }
}
