<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKjldhsJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKjldhsJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKjldhsJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKjldhsJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKjldhsJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'KjldhsJ',
    'container.build_id' => 'dcf905f0',
    'container.build_time' => 1673862281,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKjldhsJ');
