<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1e96TnN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1e96TnN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1e96TnN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1e96TnN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1e96TnN\App_KernelDevDebugContainer([
    'container.build_hash' => '1e96TnN',
    'container.build_id' => 'fdd7ea3c',
    'container.build_time' => 1673422253,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1e96TnN');
