<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container1e96TnN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1e96TnN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1e96TnN.legacy');
=======
if (\class_exists(\Container6vBF2Ok\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6vBF2Ok/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6vBF2Ok.legacy');
>>>>>>> 562b9bf7067eb450b37191d10a3bd6e0c708cb9d

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container1e96TnN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1e96TnN\App_KernelDevDebugContainer([
    'container.build_hash' => '1e96TnN',
    'container.build_id' => '79fc174a',
    'container.build_time' => 1673344213,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1e96TnN');
=======
    \class_alias(\Container6vBF2Ok\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6vBF2Ok\App_KernelDevDebugContainer([
    'container.build_hash' => '6vBF2Ok',
    'container.build_id' => 'eed5b5e8',
    'container.build_time' => 1673002200,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6vBF2Ok');
>>>>>>> 562b9bf7067eb450b37191d10a3bd6e0c708cb9d
